name:                cheatsheet
version:             0.1.0.0
github:              "githubuser/cheatsheet"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cheatsheet#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- optics
- optics-core
- unordered-containers
- containers

library:
  source-dirs: src

executables:
  cheatsheet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cheatsheet

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cheatsheet

  doctest:
    main:            Spec.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cheatsheet
    - doctest
    - Glob

default-extensions:
  # NOTE: Keep in sync with ./doctest/Spec.hs
  - OverloadedStrings
  - OverloadedLabels
  - AllowAmbiguousTypes
  - InstanceSigs
  - DataKinds
  - ScopedTypeVariables
  - KindSignatures
  - LambdaCase
  - RecordWildCards
  - DeriveAnyClass
  - DerivingStrategies
  - DeriveGeneric
  - FlexibleInstances
  - TypeApplications
  - DuplicateRecordFields
  - TemplateHaskell
  - TupleSections
  - NumericUnderscores
  - TypeOperators
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - NamedFieldPuns
